---
title: Tekst schrijven met de Python schildpad
hero_image: images/banner.png
description: Tekst schrijven met de Python schildpad
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: false
interests: "grafisch"
technologies: "python, turtle"
steps:
  - 
    title: Tekst schrijven
