---
title: Skrive tekst med Python skilpadde
hero_image: images/banner.png
description: Skrive tekst med Python skilpadde
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: false
interests: "graphics"
technologies: "python, turtle"
steps:
  - 
    title: Skrive tekst
