---
title: Escrever texto com tartaruga Python
hero_image: images/banner.png
description: Escrever texto com tartaruga Python
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: false
interests: "gráficos"
technologies: "python, tartaruga"
steps:
  - 
    title: Escrever texto
