---
title: Schreiben von Text mit Python Turtle
hero_image: images/banner.png
description: Schreiben von Text mit Python Turtle
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: false
interests: "graphics"
technologies: "python, turtle"
steps:
  - 
    title: Text schreiben
