---
title: Writing text with Python turtle
hero_image: images/banner.png
description: Writing text with Python turtle
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: false
interests: "grafică"
technologies: "python, turtle"
steps:
  - 
    title: Writing text
