---
title: Escrevendo texto com o tartaruga do Python
hero_image: images/banner.png
description: Escrevendo texto com o tartaruga do Python
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: false
interests: "graphics"
technologies: "python, turtle"
steps:
  - 
    title: Escrever o texto
