---
title: كتابة نص باستخدام Python turtle
hero_image: images/banner.png
description: كتابة نص باستخدام Python turtle
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: false
interests: "graphics"
technologies: "python, turtle"
steps:
  - title: كتابة نص
