---
title: Writing text with Python turtle
hero_image: images/banner.png
description: Writing text with Python turtle
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: false
interests: "그래픽"
technologies: "python, turtle"
steps:
  - 
    title: 글쓰기
