---
title: Pisanie tekstu za pomocą żółwia w Pythonie
hero_image: images/banner.png
description: Pisanie tekstu za pomocą żółwia w Pythonie
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: false
interests: "grafika"
technologies: "python, żółw"
steps:
  - 
    title: Pisanie tekstu
