---
title: Python turtle mod端l端 ile metin yazma
hero_image: images/banner.png
description: Python turtle mod端l端 ile metin yazma
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: false
interests: "graphics"
technologies: "python, turtle"
steps:
  - title: Metin yazma
